<?php

namespace Xiehe\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * hospitalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hospitalRepository extends EntityRepository
{
}
