<?php

namespace Proxies\__CG__\Xiehe\WebBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class question extends \Xiehe\WebBundle\Entity\question implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'id', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'title', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'text', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'createTime', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'originalEditionId', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'creater', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'answers', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'classifications');
        }

        return array('__isInitialized__', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'id', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'title', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'text', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'createTime', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'originalEditionId', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'creater', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'answers', '' . "\0" . 'Xiehe\\WebBundle\\Entity\\question' . "\0" . 'classifications');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (question $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', array($title));

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setText($text)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setText', array($text));

        return parent::setText($text);
    }

    /**
     * {@inheritDoc}
     */
    public function getText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getText', array());

        return parent::getText();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateTime($createTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateTime', array($createTime));

        return parent::setCreateTime($createTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateTime', array());

        return parent::getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalEditionId($originalEditionId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalEditionId', array($originalEditionId));

        return parent::setOriginalEditionId($originalEditionId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalEditionId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalEditionId', array());

        return parent::getOriginalEditionId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreater(\Xiehe\WebBundle\Entity\user $creater = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreater', array($creater));

        return parent::setCreater($creater);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreater()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreater', array());

        return parent::getCreater();
    }

    /**
     * {@inheritDoc}
     */
    public function addAnswer(\Xiehe\WebBundle\Entity\answer $answers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAnswer', array($answers));

        return parent::addAnswer($answers);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAnswer(\Xiehe\WebBundle\Entity\answer $answers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAnswer', array($answers));

        return parent::removeAnswer($answers);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswers', array());

        return parent::getAnswers();
    }

    /**
     * {@inheritDoc}
     */
    public function addClassification(\Xiehe\WebBundle\Entity\Classification $classifications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClassification', array($classifications));

        return parent::addClassification($classifications);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClassification(\Xiehe\WebBundle\Entity\Classification $classifications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClassification', array($classifications));

        return parent::removeClassification($classifications);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassifications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassifications', array());

        return parent::getClassifications();
    }

}
